"""ArtifactDiff public package interfaces."""

from artifactdiff.contract import (
    ClauseLabel,
    ClauseSelector,
    ContractClause,
    ContractDocument,
    EntityKind,
    EvidenceRef,
    LanguageKind,
    LanguageProfile,
    ProtectedEntity,
    ProtectedRegion,
    ProtectedRegionKind,
    SelectorMatch,
    SelectorResolution,
    SelectorResolutionStatus,
    detect_language,
    resolve_baseline,
    resolve_candidate,
)
from artifactdiff.models import (
    BlockRef,
    ComparisonResult,
    ComparisonSummary,
    ContentBlock,
    ContentType,
    DocumentSnapshot,
    PageSnapshot,
    Rect,
    SemanticChange,
    SourceDescriptor,
    VisualPageChange,
)

__all__ = [
    "BlockRef",
    "ClauseLabel",
    "ClauseSelector",
    "ComparisonResult",
    "ComparisonSummary",
    "ContentBlock",
    "ContentType",
    "ContractClause",
    "ContractDocument",
    "DocumentSnapshot",
    "EntityKind",
    "EvidenceRef",
    "LanguageKind",
    "LanguageProfile",
    "PageSnapshot",
    "ProtectedEntity",
    "ProtectedRegion",
    "ProtectedRegionKind",
    "Rect",
    "SelectorMatch",
    "SelectorResolution",
    "SelectorResolutionStatus",
    "SemanticChange",
    "SourceDescriptor",
    "VisualPageChange",
    "detect_language",
    "resolve_baseline",
    "resolve_candidate",
]
